name: AnyRouter
on:

  workflow_dispatch:
  schedule:
    - cron: "5 18 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
        env:
          USER_ID: ${{ secrets.USER_ID }}
          SESSION: ${{ secrets.SESSION }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
      - run: npm install
      - run: npx playwright install chromium --with-deps
      - run: node index.js
